### ISSUE TITLE
VBA Excel personalized email

### ISSUE THREAD

**Issue by cheshi-mantu** [cheshi-mantu/cvsender_vba#1]
as an end user I want script to create personalized email to prevent recipients recognize incoming messasge as spam.
script must start a message with Hello, %given name%

**Comment by uroshm** [comment]
Are you saying that by having the text "Hello _name_", the email server will not flag them as spam?

Or are you saying that you are wishing to create a script that somehow circumvents the security feature?

The latter seems not do-able.

**Comment by cheshi-mantu** [comment]
my aim is to automate p2p formal mails exchange, not to create spam sending machine, i.e. i want to be nicer.
I use this to send CV to headhunters or remind vendors to send additional documents which is plenty of similar messages (up to 100 and sometimes more)

> Are you saying that by having the text "Hello name", the email server will not flag them as spam?
